Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> print("Hisssss...)
...       
SyntaxError: unterminated string literal (detected at line 1)
>>> print("Hisssss...")
...       
Hisssss...
>>> Hisssss...
...       
SyntaxError: invalid syntax
>>> "Hisssss..."
...       
'Hisssss...'
>>> 
>>> print()
...       

>>> print("...")
...       
...
>>> quit
...       
Use quit() or Ctrl-D (end-of-file) to exit
>>> q
...       
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    q
NameError: name 'q' is not defined
>>> quit()
...       
>>> clear
...       
Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    clear
NameError: name 'clear' is not defined
